### ISSUE TITLE
How to set the camera parameters??

### ISSUE THREAD

**Issue by fiorano10** [slightech/MYNT-EYE-ROS-Wrapper#12]
How to change these params?

Gain: min=0, max=48, default=24
Brightness: min=0, max=240, default=120
Contrast: min=0, max=255, default=127
AutoExposure: min=0, max=1, default=0
Maxgain: min=0, max=48, default=48
MaxExposureTime: min=0, max=240, default=240
Desired brightness: min=0, max=255, default=192
ImuFrequency: min=100, max=500, default=200
IrControl: min=0, max=160, default=0
Hdr: min=0, max=1, default=0
FrameRate: min=10, max=60, default=25

**Comment by yangruixuan** [comment]
MYNT EYE 1.x SDK and wrapper is no longer supported. Please upgrade to 2.x SDK and firmware and use the wrapper inside.
MYNT EYE 2.x SDK https://github.com/slightech/MYNT-EYE-SDK-2
MYNT EYE 2.x Guide https://slightech.github.io/MYNT-EYE-SDK-2-Guide/
