### ISSUE TITLE
No depth/camera_info topic

### ISSUE THREAD

**Issue by fiorano10** [slightech/MYNT-EYE-ROS-Wrapper#13]
There is no depth/camera_info topic, is it aligned to either of the cameras or do I have to do it?

**Comment by yangruixuan** [comment]
MYNT EYE 1.x SDK and wrapper is no longer supported. Please upgrade to 2.x SDK and firmware and use the wrapper inside.
MYNT EYE 2.x SDK https://github.com/slightech/MYNT-EYE-SDK-2
MYNT EYE 2.x Guide https://slightech.github.io/MYNT-EYE-SDK-2-Guide/
