### ISSUE TITLE
ROS problem

### ISSUE THREAD

**Issue by dvalenciar** [slightech/MYNT-EYE-ROS-Wrapper#14]
Hello.
I already installed the MYNT EYE SDK  and everything looks good but when i try to install the ros  package in my catking _ws i got the next error:

BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 1 packages in topological order:
-- ~~  - mynteye_ros_wrapper
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'mynteye_ros_wrapper'
-- ==> add_subdirectory(MYNT-EYE-ROS-Wrapper)
CMake Error at MYNT-EYE-ROS-Wrapper/CMakeLists.txt:13 (message):
  MYNTEYE_SDK_ROOT environment variable not found.

-- Configuring incomplete, errors occurred!
See also "/home/david/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/david/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

Any idea why ?

thank you

**Comment by apollom** [comment]
I have the same problem.
How did you solve it.

**Comment by dvalenciar** [comment]
I re-installed Ubuntu and ROS, That fixed the problem

**Comment by marekskocz** [comment]
Exactly same issue here:
- installed Mynteye SDK 2, everything seems to work fine.
- Trying to catkin_make the ROS wrapper, but fails due to following issue:
                      MYNTEYE_SDK_ROOT environment variable not found.

Anybody has a fix for this (please other than re-install Ubuntu and ROS)?

**Comment by marcinolokk** [comment]
It's kind of a late reply, but it seems like the environments are not set correctly.
If anyone else has the problem, adding env in ~/.bashrc : "export MYNTEYE_SDK_ROOT="/YOUR/MYNTEYE-SDK/DIR" 
solved this issue
