### ISSUE TITLE
Cannot disable disparity computation

### ISSUE THREAD

**Issue by mpkuse** [slightech/MYNT-EYE-ROS-Wrapper#16]
Hi,
I did get the mynt eye ros wrapper. It does output the images.

However, here are my issues:
a. I cannot seem to disable the disparity computation
In the launch file, i edit
```
  <!-- stream toggles -->

  <arg name="enable_left_rect" default="false" />
  <arg name="enable_right_rect" default="false" />
  <arg name="enable_disparity" default="false" />
  <arg name="enable_disparity_norm" default="false" />
  <arg name="enable_points" default="false" />
  <arg name="enable_depth" default="false" />
```
Still for some reason it outputs the disparity. I just want the stereo image not the disparity for now. 
Disparity computation unnecessarily occupies my CPU which I do not want at the moment. 

b. I see some artifacts on the image. see attachments.
How should I fix this. ?
![screenshot from 2018-12-13 16-33-45](https://user-images.githubusercontent.com/10494231/49925843-0179c400-fef5-11e8-9aaf-6d28c0b0c2a2.png)

c. Is this a gray only camera or is it possible to get color images from it?

**Comment by BernardinD** [comment]
Did you ever figure this out?
