### ISSUE TITLE
camera.h no such file

### ISSUE THREAD

**Issue by ibaranov-cp** [slightech/MYNT-EYE-ROS-Wrapper#17]
When running catkin_make, I get:

`/catkin_ws/src/MYNT-EYE-ROS-Wrapper/src/mynteye_ros_wrapper_nodelet.cpp:20:20: fatal error: camera.h: No such file or directory
compilation terminated.
MYNT-EYE-ROS-Wrapper/CMakeFiles/MYNTWrapper.dir/build.make:62: recipe for target 'MYNT-EYE-ROS-Wrapper/CMakeFiles/MYNTWrapper.dir/src/mynteye_ros_wrapper_nodelet.cpp.o' failed
make[2]: *** [MYNT-EYE-ROS-Wrapper/CMakeFiles/MYNTWrapper.dir/src/mynteye_ros_wrapper_nodelet.cpp.o] Error 1
CMakeFiles/Makefile2:3079: recipe for target 'MYNT-EYE-ROS-Wrapper/CMakeFiles/MYNTWrapper.dir/all' failed
make[1]: *** [MYNT-EYE-ROS-Wrapper/CMakeFiles/MYNTWrapper.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed
`

The device itself and SDK examples work fine.
My ROS environment is fine (I can build packages, source them, etc)

**Comment by ibaranov-cp** [comment]
Ah, related to this issue:
https://github.com/raulmur/ORB_SLAM2/issues/535

**Comment by chrissunny94** [comment]
@ibaranov-cp  , 

Where do i need to ,add the line "-lboost_system" .

**Comment by WaldenLeefx** [comment]
@ibaranov-cp,
How exactly did you solve that problem? I'm new to Cmakelist and puzzled by that for few day.
Thanks for a lot.

**Comment by ibaranov-cp** [comment]
It's been a while, but add the line "-lboost_system" before the bracket here: https://github.com/slightech/MYNT-EYE-ROS-Wrapper/blob/master/CMakeLists.txt#L68
Similar to other lines in the target_link_libraries section

**Comment by WaldenLeefx** [comment]
@ibaranov-cp,
I have tried your method, still failed, any ideas about that(#22 )? Thanks anyway.

**Comment by ibaranov-cp** [comment]
Sorry, that's what worked for me.
