### ISSUE TITLE
Can this run in Ubuntu 14.04 ,ros indigo

### ISSUE THREAD

**Issue by wangliuliu** [slightech/MYNT-EYE-ROS-Wrapper#2]

**Comment by nianga1988** [comment]
yes，it is

**Comment by wangliuliu** [comment]
I can run SDK Samples,but fail to launch ros node ,error information as follows:
[mynteye_ros_wrapper-1] process has died [pid 4067, exit code -11, cmd /home/wzy/catkin_ws/devel/lib/mynteye_ros_wrapper/mynteye_wrapper_node __name:=mynteye_ros_wrapper __log:=/home/wzy/.ros/log/90ac4fd2-bab1-11e7-9113-309c2322c2a1/mynteye_ros_wrapper-1.log].
log file: /home/wzy/.ros/log/90ac4fd2-bab1-11e7-9113-309c2322c2a1/mynteye_ros_wrapper-1*.log
all processes on machine have died, roslaunch will exit

**Comment by nianga1988** [comment]
加QQ群558718151
