### ISSUE TITLE
Can't build with MYNT-EYE-D-SDK

### ISSUE THREAD

**Issue by stoneking** [slightech/MYNT-EYE-ROS-Wrapper#21]
I want to use the MYNT-EYE-ROS-Wrapper with my Mynt Eye P depth camera, on an ubuntu 16.04 platform with ROS kinetic.

At first, catkin_make could complained, when compiling mynteye_ros_wrapper_nodelet.cpp, that camera.h could not be found.
After modifying CMakeLists.txt to point to the appropriate ${MYNT_SDK_DIR}/include/mynteyed include directory, catkin_make complains:  
     mynteye_ros_wrapper_nodelet.cpp:52:5: error: ‘mynteye’ does not name a type
             mynteye::Camera cam;

Also, even after pointing to the correct include directory, catkin_make cannot find utility.h, calibration_parameters.h, and init_parameters.h.

Does the ROS wrapper support the Mynt Eye P camera?

Thanks.

**Comment by harjeb** [comment]
Please use [MYNT-EYE-D-SDK](https://github.com/slightech/MYNT-EYE-D-SDK) and [ros install doc](https://mynt-eye-d-sdk.readthedocs.io/en/latest/sdk/install_ros.html)
