### ISSUE TITLE
Error: Open camera failed

### ISSUE THREAD

**Issue by kanishkaganguly** [slightech/MYNT-EYE-ROS-Wrapper#4]
There seems to be an issue with the ROS wrapper for the SDK, I keep getting the error `Error: Open camera failed` with the ROS launch file and the node.
I am able to run the normal SDK examples successfully, so the camera seems to be working properly.

**Comment by somebodyus** [comment]
I am facing this problem too. Do you have any solutions?

**Comment by yangruixuan** [comment]
Please change the camera index in launch file

**Comment by somebodyus** [comment]
Great! That solves my problem.

**Comment by kanishkaganguly** [comment]
Thanks, solved my issue as well.
