### ISSUE TITLE
error: ‘class mynteye::Camera’ has no member named ‘GetTimestamp’

### ISSUE THREAD

**Issue by somebodyus** [slightech/MYNT-EYE-ROS-Wrapper#5]
I use ROS Kinetic and mynteye-1.5-linux-x64-gcc5-opencv-3.2.0.
Compiling the MYNT-EYE-ROS-Wrapper package gives me the error:
 `error: ‘class mynteye::Camera’ has no member named ‘GetTimestamp’`

**Comment by yangruixuan** [comment]
Please use the latest SDK and firmware

**Comment by somebodyus** [comment]
Using the latest SDK solves this problem.
However, I would like to suggest that the compatible version of SDK should be clearly indicated on the web page.

**Comment by yangruixuan** [comment]
Good advice
