### ISSUE TITLE
IMU output rate unstable

### ISSUE THREAD

**Issue by HaifengSu** [slightech/MYNT-EYE-ROS-Wrapper#8]
Hi, I have been using mynt-eye for SLAM algorithm evaluation. The frame rate of IMU topic is very unstable during the test. If I set the rate to 500Hz IMU 50Hz Camera, the IMU changes from 300Hz to 480Hz approximately, never reach 500 and the rate is not constant. Do you have any idea to fix this issue? I tried to use ROS adjust the frequency of IMU topic, but the result was no good. Thank you!

**Comment by joinAero** [comment]
* What's version of ROS?
* What's version of the firmware?

Besides, you could test the IMU rate without ROS by run sample ``camera_test`` of SDK. What' the result?


In ROS Wrapper, you could test the IMU rate which published:

* Edit `mynteye_ros_wrapper_nodelet.cpp` and uncomment these macro,

    ```
    #define VERBOSE
    #define VERBOSE_TO_FILE
    ```

* The result will be saved to `~/.ros/imus_publish.txt`.

**Comment by fiorano10** [comment]
@HaifengSu How did you set the frame rate and IMU frequency in ROS?

**Comment by yangruixuan** [comment]
MYNT EYE 1.x SDK and wrapper is no longer supported. Please upgrade to 2.x SDK and firmware and use the wrapper inside.
MYNT EYE 2.x SDK https://github.com/slightech/MYNT-EYE-SDK-2
MYNT EYE 2.x Guide https://slightech.github.io/MYNT-EYE-SDK-2-Guide
