### ISSUE TITLE
Global Status:Fixed Frame No tf data. Actual error: Fixed Frame [odom] does not exist

### ISSUE THREAD

**Issue by wmj1238** [slightech/MYNT-EYE-ROS-Wrapper#9]
Hi  ,
When I use the MYNT-EYE , this issue is occoured in rviz. The image can display and everything else is normal.
Could you help me resolve this question ?
Thank you very much .

**Comment by yangruixuan** [comment]
MYNT EYE 1.x SDK and wrapper is no longer supported. Please upgrade to 2.x SDK and firmware and use the wrapper inside.
MYNT EYE 2.x SDK https://github.com/slightech/MYNT-EYE-SDK-2
MYNT EYE 2.x Guide https://slightech.github.io/MYNT-EYE-SDK-2-Guide
